server:
  tomcat.max-threads: 100
  servlet:
    context-path: "/mynewapp"
management:
  endpoints:
   enabled-by-default: true
   web.exposure.include: "*"
security.ignored: /**
logging:
  level:
    org.springframework: INFO
spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: sa
    driverClassName: "org.h2.Driver"
    password: password
  jpa.database-platform: "org.hibernate.dialect.H2Dialect"
  security:
    user.name: vikram
    user.password: vikram
    user.roles: VIEWER,WRITER
commmonServerConfig:
  jpaEnabled: true
  mycustomSql: |
    select * from
      employees where login='ssingh'
  newProp: 10;
