spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: sa
    driverClassName: "org.h2.Driver"
    password: password
  jpa.database-platform: "org.hibernate.dialect.H2Dialect"
commmonServerConfig:
  jpaEnabled: false
  mycustomSql: |
    select * from
      employees where login='ssingh'
  newProp: 10;